name = "QuadraticHamiltonians"
uuid = "3e6e0849-d9f8-4894-a942-ed0587079b8f"
authors = ["cometscome <cometscome@gmail.com> and contributors"]
version = "0.0.1"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
